nginx:
  image: nginx
  ports:
    - 80:80
  links:
    - php
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

  volumes_from:
    - php


php:
  image: sbusso/php-fpm-ion
  expose:
    - 9000
  volumes:
    - ./www:/www
  links:
    - db

db:
  image: sbusso/mariadb
  volumes:
    - /var/lib/mysql/
    - ./data:/data
  expose:
    - 3306
  env_file:
    - db.env
